// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAetSDnHI0MFWMwu3K7LG8wDda55OT-sV8',
    appId: '1:361858074560:web:61110b0add553018166a25',
    messagingSenderId: '361858074560',
    projectId: 'notes-f7ffd',
    authDomain: 'notes-f7ffd.firebaseapp.com',
    storageBucket: 'notes-f7ffd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD97UFd6v6HK7SS4hcg8UsQE7qfkX0DsPA',
    appId: '1:361858074560:android:4fdf2410d15c5fef166a25',
    messagingSenderId: '361858074560',
    projectId: 'notes-f7ffd',
    storageBucket: 'notes-f7ffd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDsipeSmmKgTis_ypvd6mjvqNImXHOqjM',
    appId: '1:361858074560:ios:bceadfbb66c4194b166a25',
    messagingSenderId: '361858074560',
    projectId: 'notes-f7ffd',
    storageBucket: 'notes-f7ffd.appspot.com',
    iosClientId: '361858074560-v02pvmps7l0q0au1g5ppeasp5jkum2vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDsipeSmmKgTis_ypvd6mjvqNImXHOqjM',
    appId: '1:361858074560:ios:f7b89aa74a077b51166a25',
    messagingSenderId: '361858074560',
    projectId: 'notes-f7ffd',
    storageBucket: 'notes-f7ffd.appspot.com',
    iosClientId: '361858074560-ru9gn3r33hrumso6i623ihe1f1lpqrms.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp.RunnerTests',
  );
}
